"""auto-votes

Revision ID: 6321ea2d6e75
Revises: d11580bd0df7
Create Date: 2022-01-14 20:49:13.662784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6321ea2d6e75'
down_revision = 'd11580bd0df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
